spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: MY-JWT-SECRET
  duration: 86400

security:
  oauth2:
    client:
      client-id: cupcake
      client-secret: cupcake123