spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}

security:
  oauth2:
    client:
      client-id: ${CLIENT_ID:dscatalog}
      client-secret: ${CLIENT_SECRET:dscatalog123}